config/routes.rb
Rails.application.routes.draw do
  namespace :public do
    get 'homes/top'
    get 'homes/about'
  end
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    root to: 'homes#top'
    resources :items, only:[:new, :create, :index, :show, :edit, :update]
    resources :customers, only:[:index, :show, :edit, :update]
    resources :orders, only:[:show]
  end

  namespace :public do
    root to: 'homes#top'
    get 'about' => 'homes#about'
    get 'customers/show'
    get 'customers/edit'
    get 'customers/unsubscribe'
    patch 'customers/withdraw'
    resources :customers, only:[:update]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
end

app/controllers/admin/confirmations_controller.rb
# frozen_string_literal: true

class Admin::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customer_path
  end

  private

  def customer_params
    params.require(:customer).permit(:first_name, :last_name, :first_name_kana, :last_name_kana, :postal_code, :address, :telephone, :email, :is_deleted)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.all
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)
  end

  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item.id)
  end

  private

  def item_params
    params.require(:item).permit(:name, :introduction, :price, :is_active, :image)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
  end
end

app/controllers/admin/passwords_controller.rb
# frozen_string_literal: true

class Admin::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/admin/registrations_controller.rb
# frozen_string_literal: true

class Admin::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    admin_customer_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-10">
      <h4><span class="bg-secondary"><%= @customer.last_name %><%= @customer.first_name %>さんの会員情報編集者</span></h4>
      <%= form_with model: @customer, url: admin_customer_path(@customer.id), method: :patch  do |f| %>
        <table>
          <tr>
            <th>会員ID</th>
            <th><p><%= @customer.id %></p></th>
          </tr>
          <tr>
            <th>氏名</th>
            <th><%= f.text_field :last_name %><%= f.text_field :first_name %></th>
          </tr>
          <tr>
            <th>フリガナ</th>
            <th><%= f.text_field :last_name_kana %><%= f.text_field :first_name_kana %></th>
          </tr>
          <tr>
            <th>郵便番号</th>
            <th><%= f.text_field :postal_code %></th>
          </tr>
          <tr>
            <th>住所</th>
            <th><%= f.text_field :address %></th>
          </tr>
          <tr>
            <th>電話番号</th>
            <th><%= f.text_field :telephone %></th>
          </tr>
          <tr>
            <th>メールアドレス</th>
            <th><%= f.text_field :email %></th>
          </tr>
          <tr>
            <th>会員ステータス</th>
            <th><%= f.text_field :is_deleted %></th>
          </tr>
          <tr>
            <th><%= f.submit '変更を保存', class: 'btn btn-success' %></th>
          </tr>
        </table>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h4><span class="bg-secondary">会員一覧</span></h4>
      <table class="table">
        <thead>
          <tr>
            <th scope="col">会員ID</th>
            <th scope="col">氏名</th>
            <th scope="col">メールアドレス</th>
            <th scope="col">ステータス</th>
          </tr>
        </thead>
        <% @customers.each do |customer| %>
        <tbody>
          <tr>
            <th scope="row"><%= customer.id %></th>
            <td><%= customer.last_name %><%= customer.first_name %></td>
            <td><%= customer.email %></td>
            <td>?</td>
          </tr>
        </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-10">
      <h4><span class="bg-secondary"><%= @customer.last_name %><%= @customer.first_name %>さんの会員詳細</span></h4>
      <table class="table">
        <tr>
          <th><p>会員ID</p></th>
          <th><p><%= @customer.id %></p></th>
        </tr>
        <tr>
          <th><p>氏名</p></th>
          <th><p><%= @customer.last_name %><%= @customer.first_name %></p></th>
        </tr>
        <tr>
          <th><p>フリガナ</p></th>
          <th><p><%= @customer.last_name_kana %><%= @customer.first_name_kana %></p></th>
        </tr>
        <tr>
          <th><p>郵便番号</p></th>
          <th><p><%= @customer.postal_code %></p></th>
        <tr>
          <th><p>住所</p></th>
          <th><p><%= @customer.address %></p></th>
        <tr>
          <th><p>電話番号</p></th>
          <th><p><%= @customer.telephone %></p></th>
        <tr>
          <th><p>メールアドレス</p></th>
          <th><p><%= @customer.email %></p></th>
        <tr>
          <th><p>会員ステータス</p></th>
          <th><p>?</p></th>
        </tr>
      </table>
      <%= link_to "編集する", edit_admin_customer_path, class: 'btn btn-success' %>
      <%= link_to "注文履歴一覧を見る", edit_admin_customer_path, class: 'btn btn-primary' %>
    </div>
  </div>
</div>

app/views/admin/items/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h4><span class="bg-secondary">商品編集</span></h4>
      <div class="states">
        <%= form_with model: @item, url: admin_item_path(@item.id), method: :patch  do |f| %>
          <table>
            <tr>
              <th>商品画像</th>
              <th><%= f.file_field :image, accept: "image/*" %></th>
            </tr>
            <tr>
              <th>商品名</th>
              <th><%= f.text_field :name %></th>
            </tr>
            <tr>
              <th>商品説明</th>
              <th><%= f.text_area :introduction %></th>
            </tr>
            <tr>
              <th>税抜価格</th>
              <th><%= f.text_field :price %>円</th>
            </tr>
            <tr>
              <th>販売ステータス</th>
              <th><%= f.radio_button :is_active, true %>
                  <%= f.label :is_active, "販売中" %>
                  <%= f.radio_button :is_active, false %>
                  <%= f.label :is_active, "販売停止中" %>
              </th>
            </tr>
            <tr>
              <th><%= f.submit '変更を保存', class: 'btn btn-success' %></th>
            </tr>
          </table>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h4><span class="bg-secondary">商品新規登録</span></h4>
      <table>
       <tr>
         <th>商品ID</th>
         <th>商品名</th>
         <th>税抜き価格</th>
         <th>ステータス</th>
       </tr>
        <% @items.each do |item| %>
          <tr>
            <td><%= item.id %></td>
            <td><%= item.name %></td>
            <td><%= item.price %></td>
            <td>
              <% if item.is_active == true %>
                販売中
              <% else %>
                販売停止中
              <% end %>
            </td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-9">
      <h4 class=""><sapn class="bg-secondary">商品新規登録</sapn></h4>
      <%= form_with model: @item, url: admin_items_path do |f| %>
        <table>
          <tr>
            <th class="d-flex">
              <p>商品画像</p>
              <p><%= f.file_field :image, accept: "image/*" %></p>
            </th>
          </tr>
          <tr>
            <th class="d-flex">
              <p>商品名</p>
              <p><%= f.text_field :name %></p>
            </th>
          </tr>
          <tr>
            <th class="d-flex">
              <p>商品説明</p>
              <p><%= f.text_area :introduction %></p>
            </th>
          </tr>
          <tr>
            <th class="d-flex">
              <p>税抜き価格</p>
              <p><%= f.text_field :price %>円</p>
            </th>
          </tr>
          <tr>
            <th class="d-flex">
              <p>販売ステータス</p>
              <p>
                <%= f.radio_button :is_active, "sale" %>
                <%= f.label :is_active, "販売中" %>
                <%= f.radio_button :is_active, "sold_out" %>
                <%= f.label :is_active, "販売停止中" %>
              </p>
            </th>
          </tr>
          <tr>
            <th><%= f.submit '新規登録', class: 'btn btn-success' %></th>
          </tr>
        </table>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/items/show.html.erb
<div class="cantainer">
  <div class="row">
    <div class="col-10">
      <div class="wrapper d-flex">
        <div class="image">
          <p><%= image_tag @item.image, size: "200x200" %></p>
        </div>
        <div class="states">
          <table>
            <tr>
              <th>
                <p>商品名</p>
                <p><%= @item.name %></p>
              </th>
            </tr>
            <tr>
              <th>
                <p>商品説明</p>
                <p><%= @item.introduction %></p>
              </th>
            </tr>
            <tr>
              <th>
                <p>税込価格</p>
                <p><%= @item.price %></p>
              </th>
            </tr>
            <tr>
              <th>
                <p>販売ステータス</p>
                <p>
                  <% if @item.is_active == true %>
                    販売中
                  <% else %>
                    販売停止中
                  <% end %>
                </p>
              </th>
            </tr>
          </table>
        </div>
      </div>
      <%= link_to "編集する", edit_admin_item_path, class: 'btn btn-success' %>
    </div>
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h4><span class="bg-secondary">注文履歴詳細</span></h4>
      <table class="table">
        <tr>
          <th>購入者</th>
          <th><%= @order.name %></th>
        </tr>
        <tr>
          <th>注文日</th>
          <th><%= @order.created_at %></th>
        </tr>
        <tr>
          <th>配送先</th>
          <th><%= @order.addless %></th>
        </tr>
        <tr>
          <th>支払い方法</th>
          <th><%= @order.payment_method %></th>
        </tr>
        <tr>
          <th>注文ステータス</th>
          <th><%= @order.status %></th>
        </tr>
      </table>
    </div>
  </div>
</div>